export const TYPES = {
  ADD_PRODUCT: "ADD_PRODUCT",
  ADD_TO_CART: "ADD_TO_CART",
  CLEAR_CART: "CLEAR_CART",
  CLEAR_FILTER_PRODUCT: "CLEAR_FILTER_PRODUCT",
  FILTER_PRODUCT: "FILTER_PRODUCT",
  REMOVE_ONE_FROM_CART: "REMOVE_ONE_FROM_CART",
  REMOVE_ALL_FROM_CART: "REMOVE_ALL_FROM_CART",
  CREATE_ORDER: "CREATE_ORDER",
};
