export const TYPES = {
  LOGIN: "[auth] LOGIN",
  CHECKING: "[auth] CHECKING",
  LOGOUT: "[auth] LOGOUT",

  ADD_PRODUCT: "[shopping] ADD_PRODUCT",
  ADD_TO_CART: "[shopping] ADD_TO_CART",
  CLEAR_CART: "[shopping] CLEAR_CART",
  CLEAR_FILTER_PRODUCT: "[shopping] CLEAR_FILTER_PRODUCT",
  FILTER_PRODUCT: "[shopping] FILTER_PRODUCT",
  REMOVE_ONE_FROM_CART: "[shopping] REMOVE_ONE_FROM_CART",
  REMOVE_ALL_FROM_CART: "[shopping] REMOVE_ALL_FROM_CART",
  CREATE_ORDER: "[shopping] CREATE_ORDER",
  REMAINING: "[shopping] REMAINING",
  CLEAN_UP: "[shopping] CLEAN_UP",

  SHOW_STOCK: "[stock] SHOW_STOCK",
  ADD_SUPPLIER: "[stock] ADD_SUPPLIER",
  SUPPLIER_PRODUCTS: "[stock] SUPPLIER_PRODUCTS",
  PRODUCT_SELECTED: "[stock] PRODUCT_SELECTED",
  LOTE_SELECTED: "[stock] LOTE_SELECTED",
  CLEAN_UP_STOCK: "[stock] CLEAN_UP_STOCK",
};
